### ISSUE TITLE
Conversational vs formal/legal keywords

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#115]
## What do you need?

Another from Andrew Arch:

Explain/show how the word that is conversational is distinct from the formal/legal word.

Although the more sophisticated platforms and search becomes to be able to know both words, the word choice and knowing both, as an online writer is important to understanding what your customers are searching for.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/writing-for-the-web/2-optimise-your-content-for-search.html

**Comment by joolswood** [comment]
@AndrewArch to draft some words. We will work out the best place for this.

**Comment by AndrewArch** [comment]
This arose from a situation a couple of years ago when DHS used 'deceased' on their page about benefits after someone had died but the readers where searching for death/died/etc and not finding the page. In conversation people would say 'my father died' rather than 'my father is now deceased'.

Suggested content:

Be sure to use the language of your users/customers in preference to legal jargon or government-speak. Your usability testing of the information or transaction should alert you to poor understanding of problematic terms and phrases. However, before asking users, it is worth using tools like http://rewordify.com/index.php to identify areas where clarity might be required. 

Wonder about adding "If legal or 'jargon' terms *must* be used, be sure to include more colloquial  or conversational terms in the page title and/or in the 'subject' metadata."

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/44
