### ISSUE TITLE
Position for phone numbers real / fake written as code displayed dynamic mobile first to a user

### ISSUE THREAD

**Issue by LausKovu** [AusDTO/gov-au-content-guide#118]
Position for phone numbers real / fake written as code displayed dynamic mobile first to a user

As a user of government services online, I want to recognise phone numbers when scanning the screen for a phone number that I want to click to call or want to copy and paste and send to someone in a message or email or want to write down on paper without having to worry that if I dial this number on a land line that I won't be connected.
## What do you need

Need to know that the style chosen for showing phone numbers in content make sense now and takes into account future changes in telecommunications that are already known about. The guidance shall reflect best practice in terms of technology, accessibility and also have input from the Subject Matter Expert The ACMA under the Telecommunications Act. 

Also, in the entry check that phone numbers isn't underlined in the example so it looks like a click to call hyperlink but is not one.
## Which entry/section is this related to?

Phone numbers: http://content-style-guide.apps.staging.digital.gov.au/az-indexes/p.html#phone-numbers

Also relates to the UI Kit Design Guide as phone numbers today are a design pattern in terms of Schema: https://schema.org/docs/gs.html and Microdata: https://developers.google.com/schemas/formats/microdata Have been informed of this by Toby GOV.AU Developer.
## Good example

Have you seen style content elsewhere we should look at?

ACMA is the government authority for Australia's phone numbers:

www.acma.gov.au/Industry/Telco/Numbering/Numbering-Plan/all-about-numbers-ipnd-i-acma
www.acma.gov.au/Citizen/Consumer-info/All-about-numbers/Special-numbers/fictitious-numbers

**Comment by klepas** [comment]
@LausKovu could you elaborate? (:

> Need to know that the style chosen for showing phone numbers in content make sense now and takes into account future changes in telecommunications that are already known about. 

Is this about the entry specifically (http://content-style-guide.apps.staging.digital.gov.au/az-indexes/p.html#phone-numbers) or about their styling or both?

We have support in the uikit to automatically add an inline icon of our choosing based on various properties of a link, eg if it ends in `.pdf` we could append a PDF icon*… similarly, we could pick up that the link is a telephone number (because it starts with `tel:`), and add a phone icon to the link.

\* https://gov-au-ui-kit.apps.staging.digital.gov.au/section-link-styles.html

**Comment by joolswood** [comment]
@joolswood to review this task and check is done
